# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
