# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_auto_20170408_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='value',
            field=models.CharField(max_length=1),
        ),
    ]
