# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_auto_20170409_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='description',
            new_name='name',
        ),
    ]
