# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_auto_20170409_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
